### ISSUE TITLE
roadmap to v1.0

### ISSUE THREAD

**Issue by johnnychen94** [JuliaTesting/ReferenceTests.jl#58]
I believe this package has proved its usefulness, and I'd like to push it to its 1.0 stage.

Here are what I have in mind that needs to be done before it's ready:

- [ ] Split out and implement `match_reference` that returns a `Bool` #9 #12
- [ ] support multiple references in `match_reference` #47 
- [ ] deprecate `@test_reference`
- [ ] more illustrative documentation
- [ ] support image rendering using in vscode/atom #41 
- [ ] ignore whitespace for `AbstractArray{<:Number}` types

Please comment if you have any other ideas.
